Test mutation workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,5 @@
 name: Build and Test
+
 on: push
 jobs:
   build:
@@ -36,4 +37,60 @@ jobs:
             ${{ runner.os}}-node_modules-
       - name: Build ${{ matrix.java-version }}
         run: mvn -B clean test
+
+
+  mutation-check:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - uses: actions/setup-java@v4
+        with:
+          java-version: 24
+          distribution: temurin
+          cache: maven
+
+
+      # 1. Score HEAD
+      - name: Run PIT on HEAD
+        id: pit_head
+        run: |
+          mvn -B -ntp org.pitest:pitest-maven:mutationCoverage
+          SCORE=$(grep -oP "Mutation\s*Coverage[^0-9]*\K[0-9]+\.[0-9]+" -h target/pit-reports/*/index.html | head -1)
+          echo "score=$SCORE" >> $GITHUB_OUTPUT
+          echo "HEAD SCORE = $SCORE"
+
+
+      # 2. Score BASE (si PR)
+      - name: Run PIT on BASE branch
+        if: ${{ github.event_name == 'pull_request' }}
+        id: pit_base
+        run: |
+          git checkout ${{ github.event.pull_request.base.sha }}
+          mvn -B -ntp org.pitest:pitest-maven:mutationCoverage
+          BASE=$(grep -oP "Mutation\s*Coverage[^0-9]*\K[0-9]+\.[0-9]+" -h target/pit-reports/*/index.html | head -1)
+          echo "base=$BASE" >> $GITHUB_OUTPUT
+          echo "BASE SCORE = $BASE"
+
+
+      # 3. Comparaison
+      - name: Compare mutation score (fail if decreased)
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          HEAD=${{ steps.pit_head.outputs.score }}
+          BASE=${{ steps.pit_base.outputs.base }}
+
+          echo "HEAD = $HEAD"
+          echo "BASE = $BASE"
+
+          if (( $(echo "$HEAD < $BASE" | bc -l) )); then
+            echo "❌ Mutation score decreased → failing build"
+            exit 1
+          else
+            echo "✅ Mutation score is stable or improved"
+          fi
+
 
